apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aerolink-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/HirushaGamage10/Cloud-Enterprise.git'
    targetRevision: main
    path: aerolink/backend/k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
